### ISSUE TITLE
Open Tasks

### ISSUE THREAD

**Issue by joelfimian** [scg-unibe-ch/ese2016-team2#51]

**Comment by JulianSchuhmacher** [comment]
- menu-link for bookmarks: done in pull request #49

**Comment by joelfimian** [comment]
- sorted visiting times: don in pull request #54

**Comment by JulianSchuhmacher** [comment]
- button to choose between ad and auction: done in pull request #56 
- button to create alert directly from search: done in pull request #56

**Comment by joelfimian** [comment]
- I did not see any Problem with Umlauts. You also?

**Comment by JulianSchuhmacher** [comment]
I did not see them too.

**Comment by gourmetseasoningsake** [comment]
Slider arrows
Visitors refurb

All added in #63

**Comment by gourmetseasoningsake** [comment]
About was added in a previous pull req

**Comment by gourmetseasoningsake** [comment]
Movin Movout thingsbums is handled on the client as follows (only datepicker constraints):
IF movein is set THEN moveout cannot be set before movein date + 1 day (we add 1 day because we are kind people) 
IF moveout is set (before movein is set) THEN IF movein is set and movein date is later than moveout THEN moveout is set to movein date + 1 day

**Comment by gourmetseasoningsake** [comment]
Bookmark in menu is done

**Comment by gourmetseasoningsake** [comment]
register page done

**Comment by gourmetseasoningsake** [comment]
finshit placeAuction

**Comment by joelfimian** [comment]
Showcase prepared

**Comment by joelfimian** [comment]
Review done
